/*
 * generated by Xtext 2.26.0
 */
package org.itlingo.rsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class RslWebModule extends AbstractRslWebModule {
}
