/*
 * generated by Xtext 2.26.0
 */
package org.itlingo.rsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.itlingo.rsl.RslRuntimeModule;
import org.itlingo.rsl.RslStandaloneSetup;
import org.itlingo.rsl.ide.RslIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class RslWebSetup extends RslStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RslRuntimeModule(), new RslIdeModule(), new RslWebModule()));
	}
	
}
