/*
 * generated by Xtext 2.26.0
 */
package org.itlingo.rsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RslUiModule extends AbstractRslUiModule {

	public RslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
